name: renderman
environment:
  sdk: '>=2.10.0 <3.0.0'
dependencies:
  shelf: ^1.1.4
  puppeteer: ^2.0.0
  http: ^0.13.3
  dotenv: ^3.0.0
  sprintf: ^6.0.0
  crypto: ^3.0.1
  pedantic: ^1.11.0
  retry: ^3.1.0
  convert: ^3.0.0
  es_compression: ^2.0.3
